name: Check DCO Sign-off

on:
  pull_request:

jobs:
  check_dco:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check DCO Sign-off
        run: |
          # Fetch all commits from the PR branch
          git fetch origin +refs/pull/${{ github.event.pull_request.number }}/merge

          # Get commit details
          base_branch=${{ github.event.pull_request.base.ref }}
          for commit in $(git rev-list origin/${base_branch}..HEAD); do
            # Extract committer name and email
            committer_name=$(git log -1 --pretty=format:'%cn' $commit)
            committer_email=$(git log -1 --pretty=format:'%ce' $commit)

            # Check if commit message contains the correct DCO sign-off format
            if ! git log -1 --pretty=format:'%s %b' $commit | grep -q "^DCO signed and agreed by: $committer_name <$committer_email>$"; then
              echo "Error: Commit $commit must contain a DCO sign-off with correct committer details."
              exit 1
            fi
          done
